version: '3'  # Docker Compose file format version

services:  # Definitions of services to be run

  production:  # Service for the production environment
    build:  # Specifies how to build the service's container image
      context: .  # Build context is the current directory
      dockerfile: Dockerfile  # Specifies the Dockerfile to use for building the image
    ports:  # Specifies ports to expose from the container to the host machine
      - "8080"  # Maps port 8081 of the container to a random port on the host machine
    command: npm run prod -- --host  # Command to run when the container starts for production, --host expose the host port to the network

  nginx:  # Service for the Nginx server
    image: nginx:alpine  # Specifies the Docker image to use for the Nginx service
    ports:  # Specifies ports to expose from the container to the host machine
      - "8080:8080"  # Maps port 8080 of the container to port 8080 on the host machine
    volumes:  # Specifies volumes to mount from the host machine into the container
      - ./nginx.conf:/etc/nginx/nginx.conf//:ro  # Mounts the nginx.conf file to the Nginx configuration directory and makes the file in read-only mode
    depends_on:  # Specifies dependencies for this service
      - production  # Indicates that the Nginx service depends on the production service

  development:  # Service for the development environment
    build:  
      context: .  
      dockerfile: Dockerfile 
    ports:  
      - "3001:3001"
    command: npm run dev -- --host

  test:  # Service for the test environment
    build:  
      context: .
      dockerfile: Dockerfile
    command: npm run test -- --host
