enum ReduxActions {
  SET_TRAVEL = "SET_TRAVEL",
  CLEAR_TRAVEL = "CLEAR_TRAVEL",
  SET_FEEDBACK = "SET_FEEDBACK",
  CLEAR_FEEDBACK = "CLEAR_FEEDBACK",
  TOGGLE_MODE = "TOGGLE_MODE",
}

export default ReduxActions;
