enum ReduxActions {
  LOGED_IN = "LOGED_IN",
  LOGED_OUT = "LOGED_OUT",
  EDITED_ITEM = "EDITED_ITEM",
  ANSWERED_ITEM = "ANSWERED_ITEM",
  SET_CURRENT_EXPERIMENT = "SET_CURRENT_EXPERIMENT",
  UNSET_CURRENT_EXPERIMENT = "UNSET_CURRENT_EXPERIMENT",
  PEREPARE_NEXT_QUESTION = "PEREPARE_NEXT_QUESTION",
  LOAD_QUESTIONS_TO_EXP = "LOAD_QUESTIONS_TO_EXP",
}

export default ReduxActions;
